Repository SOPT-all/35-COLLABORATION-iOS-SafetyReport, pull requests merged in 2024-11, with the labels that each got.

#1 [Setting] 깃 이그노어 추가
  .gitignore
Labels: Jihoon

#3 Add/#2 - color assets 추가
  saftyReport/saftyReport/Assets.xcassets/Color/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray1.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray10.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray11.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray12.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray13.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray2.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray3.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray4.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray5.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray6.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray7.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray8.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray/gray9.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray_opacity/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray_opacity/gray13_opacity10.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray_opacity/gray13_opacity40.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray_opacity/gray13_opacity5.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray_opacity/gray13_opacity60.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray_opacity/gray1_opacity10.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/gray_opacity/gray1_opacity30.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/primary/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/primary/primary.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/primary/primary_light.colorset/Contents.json
  saftyReport/saftyReport/Assets.xcassets/Color/primary/primary_red.colorset/Contents.json
Labels: Add, Yurim

#11 Add/#5 font 설정
  .DS_Store
  saftyReport/.DS_Store
  saftyReport/saftyReport.xcodeproj/project.pbxproj
  saftyReport/saftyReport/Resource/CustomFont/TextStyle.swift
  saftyReport/saftyReport/Resource/Extension/NSAttributedString+.swift
  saftyReport/saftyReport/Resource/Extension/UIFont+.swift
  saftyReport/saftyReport/Resource/Font/Pretendard-Black.otf
  saftyReport/saftyReport/Resource/Font/Pretendard-Bold.otf
  saftyReport/saftyReport/Resource/Font/Pretendard-ExtraBold.otf
  saftyReport/saftyReport/Resource/Font/Pretendard-ExtraLight.otf
  saftyReport/saftyReport/Resource/Font/Pretendard-Light.otf
  saftyReport/saftyReport/Resource/Font/Pretendard-Medium.otf
  saftyReport/saftyReport/Resource/Font/Pretendard-Regular.otf
  saftyReport/saftyReport/Resource/Font/Pretendard-SemiBold.otf
  saftyReport/saftyReport/Resource/Font/Pretendard-Thin.otf
  saftyReport/saftyReport/Resource/Info.plist
Labels: Feat, Add, Yurim, setting

#13 [Style] 디테일 신고 View 기본 UI 작업
  saftyReport/saftyReport.xcodeproj/project.xcworkspace/xcuserdata/hoon.xcuserdatad/UserInterfaceState.xcuserstate
  saftyReport/saftyReport/SceneDelegate.swift
  saftyReport/saftyReport/Source/ReprotDetail/Cell/BaseCell.swift
  saftyReport/saftyReport/Source/ReprotDetail/Cell/ContentCell.swift
  saftyReport/saftyReport/Source/ReprotDetail/Cell/LocationCell.swift
  saftyReport/saftyReport/Source/ReprotDetail/Cell/PhoneCell.swift
  saftyReport/saftyReport/Source/ReprotDetail/Cell/PhotoCell.swift
  saftyReport/saftyReport/Source/ReprotDetail/Cell/ReportDetailSection.swift
  saftyReport/saftyReport/Source/ReprotDetail/Protocol/ConfigurableCell.swift
  saftyReport/saftyReport/Source/ReprotDetail/ReportDetailViewController.swift
  saftyReport/saftyReport/Source/ReprotDetail/ReprotDetailViewController.swift
Labels: Style, Jihoon

#18 Style/#17 - CollectionViewCell identifier Extension 추가
  saftyReport/saftyReport/Resource/Extension/UICollectionViewCell+.swift
Labels: Style, hanyeol

#15 [Style] 편의 익스텐션 추가
  saftyReport/.DS_Store
  saftyReport/saftyReport.xcodeproj/project.xcworkspace/xcuserdata/hoon.xcuserdatad/UserInterfaceState.xcuserstate
  saftyReport/saftyReport/Resource/Assets.xcassets/Color/primary/primary_orange.colorset/Contents.json
  saftyReport/saftyReport/Resource/Extension/UIFont+.swift
  saftyReport/saftyReport/Resource/Extension/UIStackView.swift
  saftyReport/saftyReport/Resource/Extension/UIView.swift
Labels: Feat, Jihoon

#23 [Style] 쉐도우 만들기
  saftyReport/saftyReport.xcodeproj/xcuserdata/hoon.xcuserdatad/xcschemes/xcschememanagement.plist
  saftyReport/saftyReport/Resource/CustomFont/CustomShadow.swift
  saftyReport/saftyReport/Resource/Extension/UIStackView+.swift
  saftyReport/saftyReport/Resource/Extension/UIView+.swift
  saftyReport/saftyReport/Source/ReprotDetail/Cell/ContentCell.swift
  saftyReport/saftyReport/Source/ReprotDetail/ReportDetailViewController.swift
Labels: Style, Jihoon

#25 Style/#10 - SafetyReportGalleryUI
  saftyReport/saftyReport/SceneDelegate.swift
  saftyReport/saftyReport/Source/Gallery/Cell/ContentsCell.swift
  saftyReport/saftyReport/Source/Gallery/Cell/MediaSelectCell.swift
  saftyReport/saftyReport/Source/Gallery/Cell/WarningCell.swift
  saftyReport/saftyReport/Source/Gallery/GalleryContentsSectionHeader.swift
  saftyReport/saftyReport/Source/Gallery/GalleryItem.swift
  saftyReport/saftyReport/Source/Gallery/GallerySectionType.swift
  saftyReport/saftyReport/Source/Gallery/GalleryViewController.swift
  saftyReport/saftyReport/Source/Gallery/Gallerydummy.swift
  saftyReport/saftyReport/Source/ReprotDetail/ReportDetailViewController.swift
Labels: Style, Hanyeol

#28 Style/#24 base alert
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/icn_cross_i_selected_white_24px.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/icn_cross_i_selected_white_24px.imageset/icn_cross_i_selected_white_24px.svg
  saftyReport/saftyReport/Source/BaseAlert/AlertManager.swift
  saftyReport/saftyReport/Source/BaseAlert/BaseOneButtonAlertView.swift
  saftyReport/saftyReport/Source/BaseAlert/BaseOneButtonAlertViewController.swift
  saftyReport/saftyReport/Source/BaseAlert/BaseTwoButtonAlertView.swift
  saftyReport/saftyReport/Source/BaseAlert/BaseTwoButtonAlertViewController.swift
  saftyReport/saftyReport/Source/BaseAlert/HowToAlertViewController.swift
Labels: Style, Yurim

#32 Setting/#26 Config 파일 및 관련 코드 사전세팅
  saftyReport/saftyReport/Network/DTO/Response/CategoryResponse.swift
  saftyReport/saftyReport/Network/DTO/Response/FailResponse.swift
  saftyReport/saftyReport/Network/DTO/Response/GalleryResponse.swift
  saftyReport/saftyReport/Network/DTO/Response/HomeResponse.swift
  saftyReport/saftyReport/Network/DTO/Response/ReportResponse.swift
  saftyReport/saftyReport/Network/Environment.swift
  saftyReport/saftyReport/Network/NetworkError.swift
Labels: Hanyeol, setting

#34 Style/#33 Gallery Detail UI
  saftyReport/saftyReport/Source/Gallery/Cell/ContentsCell.swift
  saftyReport/saftyReport/Source/Gallery/GalleryDetailViewController.swift
  saftyReport/saftyReport/Source/Gallery/GalleryViewController.swift
Labels: Feat, Style, Hanyeol

#37 Style/#36 address view UI
  saftyReport/saftyReport/Resource/Assets.xcassets/ReportImage/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/ReportImage/report_address_image.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/ReportImage/report_address_image.imageset/ReportAddressImage.svg
  saftyReport/saftyReport/Resource/Custom/TabBar/CustomTabBarItem.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/BaseCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/ContentCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/LocationCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/PhoneCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/PhotoCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/ReportDetailSection.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/ReportTypeCell.swift
  saftyReport/saftyReport/Source/ReportDetail/MockReportView.swift
  saftyReport/saftyReport/Source/ReportDetail/Protocol/ConfigurableCell.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportAddress/ReportAddressViewController.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportDetailViewController.swift
  saftyReport/saftyReport/Source/ReportDetail/ReprotDetailDummy.swift
Labels: Style, Hanyeol

#40 Style/#20 detail report icon
  saftyReport/saftyReport.xcodeproj/xcuserdata/hoon.xcuserdatad/xcschemes/xcschememanagement.plist
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/btn_i_camera.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/btn_i_camera.imageset/btn_i_camera.svg
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/btn_i_folder.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/btn_i_folder.imageset/btn_i_folder.svg
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/btn_i_location.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/btn_i_location.imageset/btn_i_location.svg
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/btn_i_mic.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/IconImage/24*24/btn_i_mic.imageset/btn_i_mic.svg
  saftyReport/saftyReport/Source/ReportDetail/Cell/BaseCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/ContentCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/LocationCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/PhoneCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/PhotoCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Items/ReportItem.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportDetailDummy.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportViewController.swift
Labels: Style, Jihoon

#44 Setting/#43 Config 파일 및 관련 코드 세팅
  saftyReport/saftyReport/Network/Environment.swift
  saftyReport/saftyReport/Resource/Info.plist
  saftyReport/saftyReport/Source/ReportDetail/ReportAddress/ReportAddressViewController.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportDetailViewController.swift
Labels: Hanyeol, setting

#45 Feat/#42 detail report do page
  saftyReport/saftyReport.xcodeproj/project.pbxproj
  saftyReport/saftyReport/Resource/Assets.xcassets/ReportImage/how_to_report_detail.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/ReportImage/how_to_report_detail.imageset/howToReportDetail.png
  saftyReport/saftyReport/Resource/Custom/CustomShadow.swift
  saftyReport/saftyReport/Resource/Custom/TabBar/CustomTabBarItem.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/ContentCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/LocationCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/PhoneCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/PhotoCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/ReportTypeCell.swift
  saftyReport/saftyReport/Source/ReportDetail/MockReportView.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportDetailViewController.swift
Labels: Feat, Jihoon

#50 Fix/#49 - .gitignore에 *.xcconfig 추가
  .gitignore
Labels: Fix, Yurim

#51 Style/#35 report category
  saftyReport/saftyReport/Resource/Extension/UITableViewCell+.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategory.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryExpandedTableViewCell.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryNormalTableViewCell.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryView.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryViewController.swift
Labels: Feat, Style, Yurim

#48 [Feat] 네트워크 기본세팅
  saftyReport/saftyReport.xcodeproj/project.pbxproj
  saftyReport/saftyReport/Network/DTO/Response/ReportResponse.swift
  saftyReport/saftyReport/Resource/Config.xcconfig
  saftyReport/saftyReport/Source/ReportDetail/ReportDetailViewController.swift
Labels: Feat, Jihoon

#53 Style/#47 Modify View
  saftyReport/saftyReport/Source/Gallery/GalleryViewController.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportAddress/ReportAddressViewController.swift
Labels: Style, Hanyeol

#57 Feat/#52 - ReportCategoryVC Snapshot
  saftyReport/saftyReport/Source/Report/ReportViewController.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategory.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryViewController.swift
Labels: Feat, Style, Yurim

#55 Style/#31 main view UI
  saftyReport/saftyReport.xcodeproj/xcuserdata/hee.xcuserdatad/xcschemes/xcschememanagement.plist
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/Ellipse5x5.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/Ellipse5x5.imageset/Ellipse 4397.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/Ellipse5x5.imageset/Ellipse 4397@2x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/Ellipse5x5.imageset/Ellipse 4397@3x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/graph_month_report.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/graph_month_report.imageset/Group 14.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/graph_month_report.imageset/Group 14@2x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/graph_month_report.imageset/Group 14@3x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/graph_year_report.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/graph_year_report.imageset/progress_bar_filled_orange_137px_21px.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/graph_year_report.imageset/progress_bar_filled_orange_137px_21px@2x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/graph_year_report.imageset/progress_bar_filled_orange_137px_21px@3x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/image_after.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/image_after.imageset/image_after.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/image_after.imageset/image_after@2x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/image_after.imageset/image_after@3x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/image_before.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/image_before.imageset/image_before.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/image_before.imageset/image_before@2x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/image_before.imageset/image_before@3x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_1.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_1.imageset/img_promotion_1.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_1.imageset/img_promotion_1@2x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_1.imageset/img_promotion_1@3x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_2.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_2.imageset/img_promotion_2.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_2.imageset/img_promotion_2@2x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_2.imageset/img_promotion_2@3x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_3.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_3.imageset/img_promotion_3.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_3.imageset/img_promotion_3@2x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/img_promotion_3.imageset/img_promotion_3@3x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/sub_graph_month_report.imageset/Contents.json
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/sub_graph_month_report.imageset/Frame 2085665457.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/sub_graph_month_report.imageset/Frame 2085665457@2x.png
  saftyReport/saftyReport/Resource/Assets.xcassets/MainViewImage/sub_graph_month_report.imageset/Frame 2085665457@3x.png
  saftyReport/saftyReport/Source/Main/Cell/BannerCell.swift
  saftyReport/saftyReport/Source/Main/Cell/FinishedReportEXCell.swift
  saftyReport/saftyReport/Source/Main/Cell/MyReportBannerCollectionViewCell.swift
  saftyReport/saftyReport/Source/Main/Cell/MyReportCell.swift
  saftyReport/saftyReport/Source/Main/MainContentsItem.swift
  saftyReport/saftyReport/Source/Main/MainContentsSectionHeader.swift
  saftyReport/saftyReport/Source/Main/MainDummy.swift
  saftyReport/saftyReport/Source/Main/MainItem.swift
  saftyReport/saftyReport/Source/Main/MainViewController.swift
Labels: Style, Heeun

#58 Style/#56 floating button
  saftyReport/saftyReport/Source/Main/Cell/BannerCell.swift
  saftyReport/saftyReport/Source/Main/Cell/ButtonTableCell.swift
  saftyReport/saftyReport/Source/Main/Cell/FinishedReportEXCell.swift
  saftyReport/saftyReport/Source/Main/Cell/MyReportBannerCollectionViewCell.swift
  saftyReport/saftyReport/Source/Main/Cell/MyReportCell.swift
  saftyReport/saftyReport/Source/Main/MainContentsItem.swift
  saftyReport/saftyReport/Source/Main/MainViewController.swift
  saftyReport/saftyReport/Source/Main/TableItem.swift
Labels: Style, Heeun

#61 Feat/#54 connect network
  saftyReport/saftyReport/Network/DTO/Response/GalleryResponse.swift
  saftyReport/saftyReport/Network/NetworkManager.swift
  saftyReport/saftyReport/Resource/Extension/UIImageView+.swift
  saftyReport/saftyReport/Source/Gallery/Cell/ContentsCell.swift
  saftyReport/saftyReport/Source/Gallery/GalleryDetailViewController.swift
  saftyReport/saftyReport/Source/Gallery/GalleryItem.swift
  saftyReport/saftyReport/Source/Gallery/GalleryViewController.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportAddress/ReportAddressViewController.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportDetailViewController.swift
Labels: Feat, Hanyeol

#63 [Style] 화면 진입시 투명도조절
  saftyReport/saftyReport/Source/ReportDetail/Cell/BaseCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/ReportTypeCell.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportDetailViewController.swift
Labels: Jihoon

#66 Feat/#59 - category 선택 뷰 네트워크 연결
  saftyReport/saftyReport/Network/DTO/Response/CategoryResponse.swift
  saftyReport/saftyReport/Resource/Extension/String+.swift
  saftyReport/saftyReport/Source/ReportCategory/CustomCategory.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategory.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryExpandedTableViewCell.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryNormalTableViewCell.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryView.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryViewController.swift
Labels: Feat, Yurim

#68 Feat/#67 - 카테고리 선택뷰 신고하기 버튼 액션 설정
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryExpandedTableViewCell.swift
  saftyReport/saftyReport/Source/ReportCategory/ReportCategoryViewController.swift
Labels: Feat, Yurim

#65 Feat/#62 - 체크박스와 사용 버튼 연동. 근데 이제 약간의 오류를 곁들인
  saftyReport/saftyReport/Network/NetworkManager.swift
  saftyReport/saftyReport/Source/Gallery/Cell/ContentsCell.swift
  saftyReport/saftyReport/Source/Gallery/GalleryDetailViewController.swift
  saftyReport/saftyReport/Source/Gallery/GalleryViewController.swift
Labels: Feat, Hanyeol

#72 Feat/#71 photodelegate
  saftyReport/saftyReport/Resource/Config.xcconfig
  saftyReport/saftyReport/Source/Gallery/Cell/ContentsCell.swift
  saftyReport/saftyReport/Source/Gallery/GalleryViewController.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/PhotoCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/SelectedCell.swift
Labels: Jihoon

#75 Feat/#73 connect flow
  saftyReport/saftyReport/Resource/Custom/TabBar/CustomTabBarItem.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/LocationCell.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportAddress/ReportAddressViewController.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportDetailViewController.swift
Labels: Feat, Hanyeol

#79 Fix/#78 - 사진 안불러와지던 거 수정
  saftyReport/saftyReport/Source/Gallery/GalleryViewController.swift
Labels: Fix, Hanyeol

#81 Docs/#80 - Update README.md
  README.md
Labels: Docs, Hanyeol

#82 [feat] 최종 비동기 코드로 전환
  saftyReport/saftyReport/Source/ReportDetail/Cell/ContentCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/PhoneCell.swift
  saftyReport/saftyReport/Source/ReportDetail/Cell/ReportTypeCell.swift
  saftyReport/saftyReport/Source/ReportDetail/ReportDetailViewController.swift
Labels: Feat, Style, Chore, Jihoon
